# Crear una cita/reserva
POST https://api-movil-rh0g.onrender.com/api/dates HTTP/1.1
Content-Type: application/json

{
  "user_id": "userId123",
  "user_name": "Nombre del usuario",
  "appointment_date": "2024-03-11T10:00:00.000Z",
  "description": "Descripción de la cita"
}


# Obtener todas las citas/reservas
GET https://api-movil-rh0g.onrender.com/api/dates

# Obtener una cita/reserva por su ID (reemplaza {appointmentId} con el ID real de la cita)
GET https://api-movil-rh0g.onrender.com/api/dates/idCita

# Actualizar una cita/reserva por su ID (reemplaza {appointmentId} con el ID real de la cita)
PUT https://api-movil-rh0g.onrender.com/api/dates/idCita
Content-Type: application/json

{
  "id_date": "cita123",
  "user_id": "userId123",
  "user_name": "Nuevo nombre del usuario",
  "appointment_date": "2024-03-11T14:00:00.000Z",
  "description": "Nueva descripción de la cita"
}

# Eliminar una cita/reserva por su ID (reemplaza {appointmentId} con el ID real de la cita)
DELETE https://api-movil-rh0g.onrender.com/api/dates/idCita
