# Crear un Pedido
POST https://api-movil-rh0g.onrender.com/api/orders HTTP/1.1
Content-Type: application/json

{
  "user_id": "65f0938c25de8e4e7acb1ac8",
  "creation_date": "2020-05-11T08:00:00.000Z",
  "delivery_date": "2024-03-15T08:00:00.000Z",
  "order_status": "delivered",
  "total_order": 20000.00,
  "products": [
    {
      "name": "auto",
      "image": "https://github.com/Dan2572/assets_erikas_homemade/blob/main/Desktop/assets/images/mu%C3%B1econieve.jpg",
      "quantity": 4,
      "price": 50.00
    },
    {
      "name": "Producto 2",
      "image": "https://github.com/Dan2572/assets_erikas_homemade/blob/main/Desktop/assets/images/mu%C3%B1econieve.jpg",
      "quantity": 1,
      "price": 50.00
    }
  ]
}

# Obtener todos los Pedidos
GET https://api-movil-rh0g.onrender.com/api/orders

#Obtener un Pedido
GET https://api-movil-rh0g.onrender.com/api/orders/orderId

#Actualizar un Peddido
PUT https://api-movil-rh0g.onrender.com/api/orders/orderId HTTP/1.1
Content-Type: application/json

{
  "order_status": "completed",
  "delivery_date": "2024-03-14T08:00:00.000Z"
}

#Eliminar un pedido
DELETE https://api-movil-rh0g.onrender.com/api/orders/65ef5826cfa9971a1882e608
