POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Nombre del usuario",
  "phone": "Teléfono del usuario",
  "document": "Documento del usuario",
  "email": "Usuario@gmail.com",
  "username": "Usuario",
  "password": "1234"
}
# Obtener todos los usuarios
GET http://localhost:3000/api/users

# Obtener un usuario por su ID (reemplaza {userId} con el ID real del usuario)
GET http://localhost:3000/api/users/65eb78970d4b7085f159e53d

# Actualizar un usuario por su ID (reemplaza {userId} con el ID real del usuario)
PUT http://localhost:3000/api/users/65eb78970d4b7085f159e53d
Content-Type: application/json

{
  "name": "Nombre del usuario actualizado",
  "phone": "Teléfono del usuario actualizado",
  "document": "Documento del usuario actualizado",
  "email": "correo@ejemplo.com",
  "username": "nombredeusuario",
  "password": "contraseña"
}
# Eliminar un usuario por su ID (reemplaza {userId} con el ID real del usuario)
DELETE http://localhost:3000/api/users/65eb78970d4b7085f159e53d


POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "DarkKing@gmail.com",
  "password": "1234"
}